#cloud-config

apt:
    sources:
        backports:
            source: "deb http://ftp.debian.org/debian stretch-backports main"

package_update: true

package_upgrade: true

packages:
    - bc
    - gdal-bin
    - git
    - jq
    - rsync
    - spatialite-bin
    - sqlite3
    - unzip
    - zip

mounts:
    - [ sdb, /mnt ]

